apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubesync
  name: kubesync-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: kubesync
  template:
    metadata:
      labels:
        app: kubesync
    spec:
      containers:
      - image: ghcr.io/ahanafy/kubesync/kubesync:v0.0.2
        imagePullPolicy: Always
        name: kubesync
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        volumeMounts:
        - mountPath: /config
          name: config-vol
          readOnly: true
      volumes:
      - name: config-vol
        secret:
          secretName: config-secret
