apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
secretGenerator:
  - name: config-secret
    files:
      - "./config.yaml"
    options:
      disableNameSuffixHash: true
