name: Publish

on:
  workflow_dispatch
  # push:
  #   branches: ["main"]
  
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.6
      - run: ko build
